- name: Install rewrite module if win_iis_rewrite_enabled
  win_url:
    url: "{{ task_item.url|default(xvt_public_repo_url) }}/{{ task_item.msi }}"
    dest: '{{ ansible_install_dir }}\{{ task_item.msi }}'

- name: Run the installer
  win_command: 'msiexec.exe /qn /i {{ ansible_install_dir }}\{{ task_item.msi }}'
