- name: Install MSI modules
  win_get_url:
    url: "{{ task_item.url|default(xvt_public_repo_url) }}/{{ task_item.msi }}"
    dest: '{{ ansible_install_dir }}\{{ task_item.msi }}'

- name: Run the installer
  win_command: 'msiexec.exe /qn /i {{ ansible_install_dir }}\{{ task_item.msi }}'
  ignore_errors: "{{ task_item.ignore_errors|default(False) }}"
