- name: Install IIS related features
  win_feature:
    name: "{{ item.name }}"
    state: present
    include_sub_features: "{{ item.include_sub_features|default(omit) }}"
    include_management_tools: "{{ item.include_management_tools|default(omit) }}"
  with_items: "{{ win_features }}"

- name: Install chocolatey pkgs
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: "{{ chocolatey_pkgs }}"
