- name: Install IIS related features
  win_feature:
    name: "{{ item.name }}"
    source: "{{ win_feature_source|default(omit) }}"
    state: present
    include_sub_features: "{{ item.include_sub_features|default(omit) }}"
    include_management_tools: "{{ item.include_management_tools|default(omit) }}"
  with_items: "{{ win_features }}"

- name: Install chocolatey pkgs
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: "{{ chocolatey_pkgs }}"

- block:
    - name: Set fact win_iis_sites_path from win_iis_sites
      set_fact:
        win_iis_sites_path: "{{ win_iis_sites|map(attribute='physical_path')|list|unique }}"
    - name: Set fact win_iis_webapplications_path from win_iis_webapplications
      set_fact:
        win_iis_webapplications_path: "{{ win_iis_webapplications|map(attribute='physical_path')|list|unique }}"
    - name: Set fact win_iis_directories
      set_fact:
        win_iis_directories: "{{ win_iis_sites_path|default([]) + win_iis_webapplications_path|default([]) }}"

- name: Make sure all physical path do exist
  win_file:
    path: '{{ item }}'
    state: directory
  with_items: "{{ win_iis_directories }}"

- name: Set fact win_iis_application_pool_parsed list from win_iis_sites
  set_fact:
    win_iis_application_pools_parsed: "{{ win_iis_sites|map(attribute='application_pool')|list|unique }}"
  when: win_iis_sites

- name: Set fact win_iis_application_pools_all
  set_fact:
    win_iis_application_pools_all: "{{ win_iis_application_pools + win_iis_application_pools_parsed|default([])|unique }}"

- name: Create Application Pool defined in win_iis_application_pools
  win_iis_webapppool:
    name: "{{ item }}"
    state: present
  with_items: "{{ win_iis_application_pools_all|default([]) }}"

- block:
    - name: Set fact win_iis_websites_parsed list from win_iis_webapplications if not provided
      set_fact:
        win_iis_websites_parsed:
          name: "{{ item }}"
      with_items: "{{ win_iis_webapplications|map(attribute='site')|list|unique }}"
      register: win_iis_websites_parsed_out

    - name: Set fact win_iis_websites
      set_fact:
        win_iis_websites_parsed: "{{ win_iis_websites_parsed_out.results|map(attribute='ansible_facts.win_iis_websites_parsed')|list }}"
  when: win_iis_webapplications

- name: Set fact win_iis_websites_all
  set_fact:
    win_iis_websites_all: "{{ win_iis_websites + win_iis_websites_parsed|default([])|unique }}"

- name: Create web sites defined in win_iis_websites
  win_iis_website:
    application_pool: "{{ item.application_pool|default(omit) }}"
    hostname: "{{ item.hostname|default(omit) }}"
    ip: "{{ item.ip|default(omit) }}"
    name: "{{ item.name }}"
    parameters: "{{ item.parameters|default(omit) }}"
    physical_path: "{{ item.physical_path|default(omit) }}"
    port: "{{ item.port|default(omit) }}"
    site_id: "{{ item.site_id|default(omit) }}"
    ssl: "{{ item.ssl|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
  with_items: "{{ win_iis_websites_all|default([]) }}"

- name: Create Web Applciation defined in win_iis_webapplications
  win_iis_webapplication:
    name: "{{ item.name }}"
    application_pool: "{{ item.application_pool|default(omit) }}"
    physical_path: "{{ item.physical_path|default(omit) }}"
    site: "{{ item.site }}"
    state: "{{ item.state|default(omit) }}"
  with_items: "{{ win_iis_webapplications|default([]) }}"
