- name: Install IIS related features
  win_feature:
    name: "{{ item.name }}"
    source: "{{ win_feature_source|default(omit) }}"
    state: present
    include_sub_features: "{{ item.include_sub_features|default(omit) }}"
    include_management_tools: "{{ item.include_management_tools|default(omit) }}"
  with_items: "{{ win_features }}"

- name: Install chocolatey pkgs
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: "{{ chocolatey_pkgs }}"

- name: Set fact win_iis_websites_path from win_iis_websites
  set_fact:
    win_iis_websites_path: "{{ win_iis_websites|map(attribute='physical_path')|list|unique }}"

- name: Set fact win_iis_webapplications_path from win_iis_webapplications
  set_fact:
    win_iis_webapplications_path: "{{ win_iis_webapplications|map(attribute='physical_path')|list|unique }}"

- name: Set fact win_iis_directories
  set_fact:
    win_iis_directories: "{{ (win_iis_websites_path + win_iis_webapplications_path)|unique }}"

- name: Make sure all physical path do exist
  win_file:
    path: '{{ item }}'
    state: directory
  with_items: "{{ win_iis_directories }}"

- name: Set fact win_iis_application_pools_from_sites list from win_iis_websites
  set_fact:
    win_iis_application_pools_from_sites: "{{ win_iis_websites|map(attribute='application_pool')|list|unique }}"

- name: Set fact win_iis_application_pools_all
  set_fact:
    win_iis_application_pools_all: "{{ (win_iis_application_pools + win_iis_application_pools_from_sites)|unique }}"

- name: Create Application Pool defined in win_iis_application_pools
  win_iis_webapppool:
    name: "{{ item }}"
    state: present
  with_items: "{{ win_iis_application_pools_all }}"

- name: Set fact win_iis_temp_var from win_iis_webapplications
  set_fact:
    win_iis_temp_var:
      name: "{{ item }}"
  with_items: "{{ win_iis_webapplications|map(attribute='site')|list|unique }}"
  when: item not in win_iis_websites|map(attribute='name')|list
  register: win_iis_temp_var_out

- name: Set fact win_iis_websites_from_webapplication
  set_fact:
    win_iis_websites_from_webapplication: "{{ win_iis_temp_var_out.results|map(attribute='ansible_facts.win_iis_temp_var')|list }}"

- name: Set fact win_iis_websites_all
  set_fact:
    win_iis_websites_all: "{{ win_iis_websites + win_iis_websites_from_webapplication }}"

- name: Create web sites defined in win_iis_websites
  win_iis_website:
    application_pool: "{{ item.application_pool|default(omit) }}"
    hostname: "{{ item.hostname|default(omit) }}"
    ip: "{{ item.ip|default(omit) }}"
    name: "{{ item.name }}"
    parameters: "{{ item.parameters|default(omit) }}"
    physical_path: "{{ item.physical_path|default(omit) }}"
    port: "{{ item.port|default(omit) }}"
    site_id: "{{ item.site_id|default(omit) }}"
    ssl: "{{ item.ssl|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
  with_items: "{{ win_iis_websites_all }}"

- name: Create Web Applciation defined in win_iis_webapplications
  win_iis_webapplication:
    name: "{{ item.name }}"
    application_pool: "{{ item.application_pool|default(omit) }}"
    physical_path: "{{ item.physical_path|default(omit) }}"
    site: "{{ item.site }}"
    state: "{{ item.state|default(omit) }}"
  with_items: "{{ win_iis_webapplications }}"
